version: '3.1'

services:

  mongo:
    image: mongo
    user: root
    restart: always
    expose:
      - '27017'
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/monogo-init.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${username}"
      MONGO_INITDB_ROOT_PASSWORD: "${password}"
    env_file:
      - developer.env

      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
        - 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example